version: "1.0"

services:
  # backend:
  server:
    build:
      context: ./server-app
      dockerfile: Dockerfile

    container_name: rohit-backend
    ports:
      - "4000:4000"

  # react-app
  client:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile

    container_name: rohit-frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
